let age = "24"
let birthday = "1998"
let birthdaydate = "9"
let brothersCount = "1"
let sistersCount = "1"
let family = "5"
let roadprice = "0"
let century = "2022"
let dollar = "64"
let euro = "67"
let bitcoin = "30k$"

let first = century - birthday
let second = century - age
let third = brothersCount + sistersCount
let fourth = euro * 1000
let fifth = dollar * 2.5
let sixth = bitcoin / 1000
let seven = roadprice / dollar
let eight = family - brothersCount - sistersCount
let nine = 0 / age
let ten = 35 - age